---
title: "Eastern Bering Sea"
output: html_notebook
---

## Source:
[NOAA Alaska Fisheries Science Center Groundfish Assessment Program surveys](http://www.nwfsc.noaa.gov/research/divisions/fram/groundfish/bottom_trawl.cfm)

## Related papers:  

- [Results of the 2010 Eastern and Northern Bering Sea Continental Shelf Bottom Trawl Survey of Groundfish and Invertebrate Fauna](https://www.afsc.noaa.gov/publications/afsc-tm/noaa-tm-afsc-227.pdf)  

- [Kotwicki, Stan, and Robert R. Lauth. 2013. “Detecting Temporal Trends and Environmentally-Driven Changes in the Spatial Distribution of Bottom Fishes and Crabs on the Eastern Bering Sea Shelf.” Deep Sea Research Part II: Topical Studies in Oceanography, Understanding Ecosystem Processes in the Eastern Bering Sea II, 94 (October): 231–43.](https://doi.org/10.1016/j.dsr2.2013.03.017)  

- [STEVENSON, D. E., and G. R. HOFF 2009. Species identification confidence in the eastern Bering Sea shelf survey (1982-2008). AFSC Processed Rep. 2009-04, 46 p. Alaska Fish. Sci. Cent., NOAA, Natl. Mar. Fish. Serv., 7600 Sand Point Way NE, Seattle WA 98115.](https://www.afsc.noaa.gov/Publications/ProcRpt/PR2009-04.pdf)

## How we process the data:  
- Some of the files contain extra headers in the data rows, so we remove any data rows that contain the word "LATITUDE" in the LATITUDE column.  
- We create a haulid by combining a 3 digit leading zero vessel number with a 3 digit leading zero cruise number and a 3 digit leading zero haul number, separated by "-", for example: (vessel-cruise-haul) 354-067-001.  
- If wtcpue is recorded as "-9999", we change the value to NA.  
- We remove any SCIENTIFIC spp values that contain the word "egg" or where the only value in the SCIENTIFIC field is white space.  
- Any values SCIENTIFIC values that contain the word "Atheresthes" are changed to "Atheresthes sp." because more than one genus/spp combo was used to describe the same organism over time.  This also holds true for Lepidopsetta sp., Myoxocephalus sp., Hippoglossoides sp. & Bathyraja sp.
- We group the data by haulid, stratum, stratumarea, year, lat, lon, depth,  and spp and then sum up all of the wtcpue values for each group and reassign that as the wtcpue.
