---
title: "Northeast U.S."
output: html_notebook
---

## Source:
[NOAA Northeast Fisheries Science Center Spring and Fall Bottom Trawl Surveys](http://www.nefsc.noaa.gov/femad/ecosurvey/mainpage/)

## Related information:  
- Source data for the Northeast U.S. are only available upon written request.  Details for requesting data can be found [here](https://inport.nmfs.noaa.gov/inport/item/22560).  
- [ Guide to some trawl-caught marine fishes from Maine to Cape Hatteras, North Carolina, Flescher, 1980](https://spo.nmfs.noaa.gov/content/circular-431-guide-some-trawl-caught-marine-fishes-maine-cape-hatteras-north-carolina)  
- [A brief historical review of the Woods Hole Laboratory trawl survey time series, Azarovitz, 1981](http://dmoserv3.whoi.edu/data_docs/NEFSC_Bottom_Trawl/Azarovitz1981.pdf)  
- [An Evaluation of the Bottom Trawl Survey Program of the Northeast Fisheries Center, NEFSC, 1988](https://www.st.nmfs.noaa.gov/tm/nec_image/nec052image.pdf)  
- [A historical perspective on the abundance and biomass of northeast demersal complex stocks from NMFS and Massachusetts inshore bottom trawl surveys, 1963-2002, Sosebe and Cardin, 2006](https://repository.library.noaa.gov/view/noaa/5259)   
- [Estimation of Albatross IV to Henry B. Bigelow Calibration Factors, Miller et al., 2010](https://www.nefsc.noaa.gov/publications/crd/crd1005/crd1005.pdf)
- [Northeast Fisheries Science Center Bottom Trawl Survey Protocols for the NOAA Ship Henry B. Bigelow, Politis et al., 2014](https://www.nefsc.noaa.gov/publications/crd/crd1406/)  
- [Groundfish Bottom Trawl Survey Protocols, NOAA Fisheries, 2018](https://www.fisheries.noaa.gov/resource/document/groundfish-bottom-trawl-survey-protocols)  
- [Density-Independent and Density-Dependent Factors Affecting Spatio-Temporal Dynamics of Atlantic Cod (Gadus Morhua) Distribution in the Gulf of Maine, Zengguang et al., 2018](https://doi.org/10.1093/icesjms/fsx246)
- [Technical Documentation, State of the Ecosystem Report, NEFSC, 2019](https://noaa-edab.github.io/tech-doc/)  
- [NEFSC trawl strata](neus_NEFSC_trawl_strata.pdf)  

## How we process the data:  
- We group the data by YEAR, SEASON, LAT, LON, DEPTH, CRUISE6, STATION, STRATUM, and SVSPP and sum the BIOMASS (which is reported by sex) to calculate wtcpue.  
- We create a haulid by combining a 6 digit leading zero cruise number with a 3 digit leading zero station number and a 4 digit leading zero stratum number, separated by "-", for example: (cruise-station-stratum) 456354-067-0001.  
- We convert square nautical miles to square kilometers.  
- We remove any SCINAME spp values that contain the word "egg" or "unidentified", or where the only value in the SCINAME field is white space.  
- We group the data by haulid, stratum, stratumarea, year, lat, lon, depth,  and spp and then sum up all of the wtcpue values for each group and reassign that as the wtcpue.
- We separate the trawls into Fall and Spring seasons.




