---
title: "OceanAdapt Metadata"
output: 
  github_document: 
    toc: TRUE
---
## data_raw folder   
contains data that are downloaded from the websites of various government agencies. Raw data is regionally sourced and those sources are the best place to find the most current information about the raw data:  
- [Alaska Fisheries Science Center - NOAA](https://www.afsc.noaa.gov/RACE/groundfish/survey_data/metadata_template.php?fname=RACEweb.xml) - This NOAA center provides data for the Aleutian Islands, Eastern Bering Sea, and Gulf of Alaska.  
- [Northwest Fisheries Science Center - NOAA](https://www.nwfsc.noaa.gov/research/divisions/fram/index.cfm) - This NOAA center provides data for the West Coast Triennial and West Coast Annual surveys.  
- [Gulf States Marine Fisheries online SEAMAP access ](https://seamap.gsmfc.org/documents/SEAMAP_Data_Structures.pdf) - This program provides data for the Gulf of Mexico.  
- [Northeast Fisheries Science Center](https://www.nefsc.noaa.gov/rcb/projects/ntap/) - This NOAA center provides data for the Northeast US.  
- [SEAMAP South Atlantic](https://www2.dnr.sc.gov/seamap/Account/LogOn?ReturnUrl=%2fseamap%2fReports) - This program provides data for the Southeast US.  
- [Canadian Department of Fisheries and Oceans](http://www.dfo-mpo.gc.ca/index-eng.htm) - Canada DFO provides data for the Scotian Shelf.


## compile.R script  
generates tables that vary slightly from the orignal raw data.  All of these tables can be found as RData in the [data_clean](https://github.com/mpinsky/OceanAdapt/tree/update_2019/data_clean) folder.  Descriptions of the tables follow.  
- [all-regions-full.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/all-regions-full.RData) - all of the raw data from all regions, combined, and reduced to the following columns:  

    - region - the region where the trawl survey was conducted.
    - haulid - a unique identifier of each tow.
    - year - the year the survey was conducted in %YYYY format.
    - lat - the latitude where the tow was conducted in decimal units.
    - lon - the longitude where the tow was conducted in decimal units.
    - stratum - the stratum identifier for the tow.
    - stratumarea - the area in km^2 covered by the tow.
    - depth - the depth in meters of the tow.
    - spp - the scientific name of the species observed in the tow.
    - common - the common name of the speices observed in the tow.
    - wtcpue - the weight of catch per unit effort for the species in the tow.  
- [all-regions-trimmed.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/all-regions-trimmed.RData) - the full data table above reduced to include only speices that are in present in at least 3/4 of the years for each region.  

    - region - the region where the trawl survey was conducted.
    - haulid - a unique identifier of each tow.
    - year - the year the survey was conducted in %YYYY format.
    - lat - the latitude where the tow was conducted in decimal units.
    - lon - the longitude where the tow was conducted in decimal units.
    - stratum - the stratum identifier for the tow.
    - stratumarea - the area in km^2 covered by the tow.
    - depth - the depth in meters of the tow.
    - spp - the scientific name of the species observed in the tow.
    - common - the common name of the speices observed in the tow.
    - wtcpue - the weight of catch per unit effort for the species in the tow.  
- [by-national.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/by_national.RData) - shows the national averages, reduced to only data sets with consistent methods over time.  
    
    - year - the year the survey was conducted in %YYYY format.  
    - lat - the mean latitude where the tows were conducted in decimal units.  
    - lon - the mean latitude where the tows were conducted in decimal units.  
    - depth - the mean depth in meters of the tows.  
    - lat_se - the standard error of the mean latitude for the year.  
    - lonse - the standard error of the mean longitude for the year.  
    
    - depth_se - the standard error of the mean depth for the year.  
    - numspp - the number of species observed for the year.  
- [by-region.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/by_region.RData) - shows the regional averages by year.  

    - region - the region where the trawl survey was conducted.  
    - year - the year the survey was conducted in %YYYY format.  
    - lat - the latitude where the tow was conducted in decimal units.  
    - lon - the longitude where the tow was conducted in decimal units.  
    - depth - the depth in meters of the tow.  
    - lat_se - the standard error of the mean latitude for the year.  
    - lonse - the standard error of the mean longitude for the year.  
    
    - depth_se - the standard error of the mean depth for the year.  
    - numspp - the number of species observed for the year.  
- [by-species.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/by_species.RData) - shows the annual averages by species within regions.  

    - region - the region where the trawl survey was conducted.  
    - spp - the scientific name of the species observed in the tow.  
    - common - the common name of the speices observed in the tow.  
    - year - the year the survey was conducted in %YYYY format.  
    - lat - the latitude where the tow was conducted in decimal units.  
    - lon - the longitude where the tow was conducted in decimal units.  
    - depth - the depth in meters of the tow.  
    - lat_se - the standard error of the mean latitude for the year.  
    - lonse - the standard error of the mean longitude for the year.  
    
    - depth_se - the standard error of the mean depth for the year.  
- [dat_exploded.RData](https://github.com/mpinsky/OceanAdapt/blob/update_2019/data_clean/dat_exploded.Rdata) - this file contains all speices by region in all years.   

    - region - the region where the trawl survey was conducted.  
    - haulid - a unique identifier of each tow.  
    - year - the year the survey was conducted in %YYYY format.  
    - lat - the latitude where the tow was conducted in decimal units.  
    - lon - the longitude where the tow was conducted in decimal units.  
    - stratum - the stratum identifier for the tow.  
    - stratumarea - the area in km^2 covered by the tow.  
    - depth - the depth in meters of the tow.  
    - spp - the scientific name of the species observed in the tow.  
    - common - the common name of the speices observed in the tow.  
    - wtcpue - the weight of catch per unit effort for the species in the tow.  

## plots
This folder holds plots used to check that the data is being processed as expected. 

## metaData folder
This folder contains many documents related to the collection and calculation of the data found on the OceanAdapt website.
- [00-scripts]()  
    
    - [gen-cols-units]() - a helper script to define units for generating Ecological Metadata Language (EML) documents.  
    - metaData.template.R
- [ai]()  
    
    - adp_codebook_2011.pdf  
    - AFSC_Aleutians_metadata.txt
    - ai_345fd2.csv - a sample data set  
    - metaData.ai.R - a script for generating an EML file for the ai data set.  
    - metaData_AI.xml - an EML file for the ai data set.  
    - Orr et al. 2014 species identification in GoA and AI surveys.pdf
    - species_codebook_2011.pdf  
    - Stauffer 2003 groundfish protocols.pdf
    - von Szalay et al. 2011.pdf
    - Wayne Palsson 2012-03-29 Meaning of STATION.pdf  
- [ebs]()  
    
    - AFSC EBS strata map.jpg
    - AFSC_EBS_metadata.txt  
    - EBS Spp ID Confidence 2009-04.pdf  
    - ebs_121213.csv - sample data  
    - Kotwicki & Lauth in prep.pdf  
    - Lauth 2010 NOAA-TM-AFSC-227.pdf  
    - metaData.ebs.R - a script for generating an EML file for this data set  
    - metaData_EBS.xml - an EML file for this dataset.  
- [gmex]()  
    
    - filedef.doc  
    - filestr.doc  
    - gmex_25d0f9.csv - sample data  
    - Grace et al. 2010 Marine Fish Review.pdf  
    - metaData.gmex.R - a script for generating an EML file for this data set  
    - metaData_gmex.xml - an EML doc for this dataset.  
    - Rester 2012-06-28-SEAMAP data.pdf  
    - SEAMAP-gmex_metadata.txt
    - SEDAR7_DW1.pdf  
    - SEDAR7_DW53.pdf  
- [goa]()  

    - AFSC_GOA_metadata.txt  
    - goa_2f7db6.csv - sample data
    - metaData.goa.R - a script for writing an EML document
    - metaData_GOA.xml - an EML document  
    - von Szalay et al. 2010 NOAA-TM-AFSC-208.pdf - this document was used to define the stratum areas for goa, hand typed into the goa_strata.csv file.
- [neus]()  

    - flescher1980 common trawl-caught fish.pdf
    - metaData.neus.R - a script for writing an EML file
    - metaData_NEUS.xml - an EML file
    - NEFSC trawl strata.pdf  
    - NEFSC_metadata.txt  
    - NEFSC_overview_www.gulfofmaine-census.org.html  
    - NEUS_6f90fb.csv  
    - neus_strata_map.gif  
    - neusStrata.csv  
    - SeanLucycode folder  
          
          - bigelow_fall_calibration.csv
          - bigelow_spring_calibration.csv
          - Survdat_calibrate.r
          - survey.r
    - Sosebee & Cardin 2006 inshore bottom trawl survey.pdf
    - strata_shapefile folder - contains GIS layers  
    - SVDBS Elements by Table and Column.docx
    - SVDBSvariabledefinitions.pdf
    - svspp.tsv  
    - SWG 1988 evaluation of bottom trawl - NMFS.pdf
- [ocean_adapt_docs]()  

    - oa_upload_colNames.txt
    - Ocean Adapt Report - 6-30-2016.docx
- [scot]()  
- [seus]()  
- [taxonomy]()  
- [wcann]()  
- [wctri]()  

