---
title: "Map of circles, sized by wtcpue, colored by year"
author: "Michelle Stuart"

params:
  alpha: 0.25
  subtitle_size: 11
  title_colour: dodgerblue3
  title_size: 12
  regions: west_regions
  title: "Distribution of market squid, Alaska pollock, and canary rockfish"
output:
  html_document: default
  github_document: default
  pdf_document: default
  word_document: default
subtitle: Exploring changes in marine species distributions
---

```{r setup, include=FALSE}
#This line of code installs the pacman page if you do not have it installed - if you do, it simply loads the package
if(!require(pacman))install.packages("pacman")

# change install to true if you want to install any packages listed that you don't currently have.
pacman::p_load(tidyverse, here, maps, ggthemes, grid, RColorBrewer, install = FALSE)

```

Bring in data
```{r data prep, echo=FALSE, message=FALSE, warning=FALSE, eval=FALSE, include=FALSE}
oa <- read_csv(here("data_clean", "dat_exploded.csv"), col_types = cols(
  region = col_character(),
  haulid = col_character(),
  year = col_double(),
  lat = col_double(),
  lon = col_double(),
  stratum = col_double(),
  stratumarea = col_double(),
  depth = col_double(),
  spp = col_character(),
  common = col_character(),
  wtcpue = col_double()
))

# some rows imported with problems of trailing whitespace in the stratum column
prob <- problems(oa)

prob$actual <- trimws(prob$actual)

# fix those rows in the oa data set
oa$stratum[prob$row] <- prob$actual
rm(prob)
```

Define regions
```{r}
west_regions <- c("West Coast Annual", "Aleutian Islands", "Eastern Bering Sea", "Gulf of Alaska")

east_regions <- c("Northeast US Spring", "Northeast US Fall", "Southeast US Spring", "Southeast US Fall", "Scotian Shelf Summer", "Scotian Shelf Fall", "Scotian Shelf Spring")

oa <- oa %>%
  filter(region %in% params$regions) %>%
  mutate(lon = ifelse(region == "Aleutian Islands" & !grepl("-", lon), as.numeric(paste0("-", lon)), lon))


west_coast <- map_data("world") %>% 
  filter(region == "Canada" | region == "USA") %>%
  # filter(region == "USA") %>% 
  mutate(long = ifelse(!grepl("-", long) & subregion == "Alaska", paste0("-", long), long), 
         long = as.numeric(long)) %>% 
  filter(long >= min(oa$lon), long <= max(oa$lon)) 
```

Define species
```{r west_coast}
species_of_interest <- c("Doryteuthis opalescens", "Gadus chalcogrammus", "Sebastes pinniger")

oa <- oa %>% 
  filter(spp %in% species_of_interest)

oa_mean <-  oa %>% 
  group_by(region, year, spp) %>% 
  summarise(lat = mean(lat), 
            lon = mean(lon), 
            wtcpue = mean(wtcpue)) %>% 
  ungroup() %>% 
  mutate(year = as.integer(year))

map <- ggplot(data = west_coast) +
 geom_polygon(aes(x = long, y = lat, group = group), fill = "gray80", colour = "gray85") + coord_fixed(1.3)


early_map <- map +
geom_point(data = oa_mean, aes(lon, lat, size = wtcpue, color = spp, alpha = year), show.legend = TRUE) +
  # scale_color_gradient(low = "dodgerblue", high = "dodgerblue4")+
  theme_map() 
  

early_map + 
  labs(title = params$title,
  subtitle= "
  1982-2017") +
  theme(plot.title = element_text(size = params$title_size, colour = params$title_colour)) +
  theme(plot.subtitle = element_text(size = params$subtitle_size))

ggsave("west-coast-squid-pollack-rockfish.pdf")
```


