---
title: "EML metadata template"
output: html_notebook
---
```{r setup, include=FALSE}
# load libraries
library(EML)
library(emld)
library(tidyverse)
```

## Attributes
Define custom units
```{r}
## create the "unitType" table for custom unit
id <- c("decimal degrees", "kg/tow", "num/tow", NA)
dimension <- c("length", "weight", "count", NA)
unitTypes <- data.frame(
  id = id, dimension = dimension, stringsAsFactors = FALSE
)

unitList <- set_unitList(unitTypes)
```

Define the columns present in the data file
```{r}
input <- read_csv("https://raw.githubusercontent.com/pinskylab/OceanAdapt/master/data_raw/ai1983_2000.csv")
attributes <- tibble(
  attributeName = dput(names(input)), 
  attributeDefinition = c("The latitude towed in decimal degrees (numeric)", 
                          "The longitude towed in decimal degrees (numeric)", 
                          "The station id of the tow (character)", 
                          "The unique identifier of the latitude, longitude and depth of the tow (numeric)", 
                          "The year of the tow", 
                          "The date and time of the tow", 
                          "The weight caught per unit effort for this species in this tow (numeric)", 
                          "The number caught per unit effort for this species in this tow (numeric)", 
                          "The common name of the organism captured (character)", 
                          "The scientific name of the organism captured (character)", 
                          "The unique species identification number (numeric)", 
                          "The bottom depth at this location (numeric)", 
                          "The bottom temperature at this location during this tow (numeric)", 
                          "The surface temperature at this location during this tow (numeric)", 
                          "The identification number of the vessel that conducted the tow (numeric)", 
                          "The unique identifcation number for this cruise, a combination of the year and the trip number (numeric)", 
                          "The unique identification number for this haul (numeric)"), 
formatString = c(NA, NA, NA, NA, "YYYY", "mm/dd/yyyy hh:mm", 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
unit = c("dimensionless", "dimensionless", "dimensionless", "dimensionless", "dimensionless", "dimensionless", 
"kg/tow", "num/tow", "dimensionless", "dimensionless", "dimensionless", "meters", 
"celsius", "celsius",  "dimensionless",  "dimensionless", "dimensionless"), 
numberType = c("real", "real", NA, NA, NA, NA, 
"real", "real", NA, NA, NA, "integer", 
"real", "real", NA, NA, NA)
)

attributeList <- set_attributes(attributes, col_classes = c("numeric", "numeric", "character", "numeric", "Date", "Date", "numeric", "numeric", "character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))

```
## Data file format
```{r}
physical <- set_physical("https://raw.githubusercontent.com/pinskylab/OceanAdapt/master/data_raw/ai1983_2000.csv")
```

## Assemble the dataTable
```{r}
dataTable <- list(
  entityName = "ai1983_2000.csv",
  entityDescription = "Bottom Trawl dataset from the Aleutian Islands",
  physical = physical,
  attributeList = attributeList)
```

## Create methods if wanted
```{r eval=FALSE}
# this is an example
methods_file <- system.file("examples/hf205-methods.docx", package = "EML")
methods <- set_methods(methods_file)
```

## Create parties
```{r}
R_person <- person("Aaron", "Ellison", ,"fakeaddress@email.com", "cre", 
                  c(ORCID = "0000-0003-4151-6081"))
aaron <- as_emld(R_person)

others <- c(as.person("Benjamin Baiser"), as.person("Jennifer Sirota"))
associatedParty <- as_emld(others)
associatedParty[[1]]$role <- "Researcher"
associatedParty[[2]]$role <- "Researcher"

HF_address <- list(
                  deliveryPoint = "324 North Main Street",
                  city = "Petersham",
                  administrativeArea = "MA",
                  postalCode = "01366",
                  country = "USA")

publisher <- list(
                 organizationName = "Harvard Forest",
                 address = HF_address)

contact <- 
  list(
    individualName = aaron$individualName,
    electronicMailAddress = aaron$electronicMailAddress,
    address = HF_address,
    organizationName = "Harvard Forest",
    phone = "000-000-0000")
```

## Add text blocks
```{r}
title <- "Aleutian Islands bottom trawl survey"

```

